Repository TorchJD/torchjd, pull requests merged in 2024-08, with the labels that each got.

#107 Improve documentation of parallel_chunk_size
  src/torchjd/autojac/backward.py
  src/torchjd/autojac/mtl_backward.py
Labels: documentation

#108 Add table to compare aggregators
  docs/source/docs/aggregation/index.rst
Labels: documentation

#109 Add information about compatibility in installation.md
  docs/source/installation.md
Labels: documentation

#110 Improve main doc
  docs/source/index.rst
Labels: documentation

#111 Remove unused test dependency contexttimer
  pyproject.toml
Labels: ci/cd

#113 Fix unreliable relative import in interactive_plotter.py
  tests/plots/interactive_plotter.py
Labels: bug
